---
title: sql
---

```{css css_custom, code=readLines("_css_custom.css"), echo=FALSE}
```
```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

* https://www.w3schools.com/sql/default.asp  
* https://www.w3schools.com/sql/sql_quickref.asp  
* https://docs.telemetry.mozilla.org/concepts/sql_style.html

*********************************************************************

SELECT - extracts data from a database

UPDATE - updates data in a database

DELETE - deletes data from a database

INSERT INTO - inserts new data into a database

CREATE DATABASE - creates a new database

ALTER DATABASE - modifies a database

CREATE TABLE - creates a new table

ALTER TABLE - modifies a table

DROP TABLE - deletes a table

CREATE INDEX - creates an index (search key)

DROP INDEX - deletes an index

*********************************************************************

## case when

```sql
CASE
    WHEN condition1 THEN result1
    WHEN condition2 THEN result2
    WHEN conditionN THEN resultN
    ELSE result
END;
```

*********************************************************************

## group by {#group-by}

```sql
SELECT col, count(*)
FROM table
GROUP BY col;
```

*********************************************************************

## having {#having}

```sql
SELECT col1
FROM table
GROUP BY col1
HAVING COUNT(col2) > 10;
```

*********************************************************************

## order by {#order-by}

```sql
SELECT col1
FROM table
ORDER BY col2 DESC;
```

*********************************************************************

## rename

### a table

```sql
alter table table_name rename to new_table_name;
```

### a column

```sql
alter table table_name rename column "column_name" to "new_column_name";
```

*********************************************************************

## select {#select}

aggregate functions

```sql
SELECT 
  AVG(col) as avg, 
  MAX(col) as max, 
  SUM(col) as sum
FROM table;
```

```sql
SELECT COUNT(col) * 100.0 / COUNT(*) AS asdf
FROM table;
```

*********************************************************************

## where {#where}

where and or

```sql
SELECT col1
FROM table
WHERE (col2 = 1 OR col2 = 2)
AND (col3 = 'A' OR col3 = 'B');
```

where between 

```sql
SELECT col1
FROM table
WHERE col2 BETWEEN 1 AND 2; 
--BETWEEN is inclusive, i.e. the beginning and end values are included
```

where in 

```sql
SELECT col1
FROM table
WHERE col2 IN (1, 10, 100);
```

where is

```sql
-- can also use IS NOT
SELECT col1
FROM table
WHERE col2 IS NULL;
```

where like

```sql
-- can also use NOT LIKE
SELECT col1
FROM table
WHERE col2 LIKE 'asdf%';
```

where like any

```sql
select *
from table
where col like any (
  'this %',
  'that %'
)
```

*********************************************************************

## having 

The HAVING clause was added to SQL because the WHERE keyword could not be used with aggregate functions.

```sql
SELECT column_name(s)
FROM table_name
WHERE condition
GROUP BY column_name(s)
HAVING condition
ORDER BY column_name(s);
```

*********************************************************************

## create table

### new 

```sql
create table new_table_name (
    column1 datatype,
    column2 datatype,
    column3 datatype,
   ....
);
```

Example data types:

* `varchar(255)`  
* `number(38,0)`  
* `int`  

## from existing

```sql
create table new_table_name as 
    select column1, column2,...
    from existing_table_name
    where .... ;
```


*********************************************************************

## misc

```sql
split_part(x, sep, position) -- where position is zero indexed
regexp_instr
trim
iff
pivot -- snowflake only - long to wide - i.e. spread


select * from  (
    select a, b, c, d from my_table
    pivot (
        count(d) for d in (value1, value2, ....)
    )
)

unpivot -- wide to long
```


