tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "mas-cli/tap"
brew "gcc"
brew "git"
brew "htop"
brew "keychain"
brew "mas"
brew "wget"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "atom"
cask "flux"
cask "iterm2"
cask "slack"
cask "virtualbox"
cask "xquartz"
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
