---
title: shell
output: 
    github_document:
        toc: true
        toc_depth: 4
editor_options: 
  chunk_output_type: console
---

```{r knitr_config, include = FALSE}
knitr::read_chunk("_knitr_config.R")
```

******************************************************************************************

https://devhints.io/bash  
https://towardsdatascience.com/rock-the-command-line-52c4b2ea34b7  

******************************************************************************************

### Commands {#commands} 

#### awk {#awk}

Good for extracting strings and patterns from files and analysing them...

*TODO*

#### bash {#bash}

```sh
bash script.sh > output.out
```

* `$1` first command-line parameter given to the script
* `$2` second command-line parameter given to the script
* `$@` all of the command-line parameters given to the script

<!-- [Back to top](#top) -->

#### cd {#cd}

```sh
# change directory
pwd
cd ~ && pwd
cd -
cd ~/Downloads && pwd
cd -
cd ../ && pwd
cd -
```

<!-- [Back to top](#top) -->

#### chmod {#chmod}

* TODO

<!-- [Back to top](#top) -->

#### chown {#chown}

* TODO

<!-- [Back to top](#top) -->

#### crontab {#crontab}

```sh
# see a list of scheduled jobs for current user
crontab -l

# edit the list of cron jobs (opens default editor)
# e.g. in vim pres i to insert then esc :wq, or :qa! to abandon all changes
crontab -e

#  ___________  minute (0 - 59)
# |  _________  hour (0 - 23)
# | |  _______  day of month (1 - 31)
# | | |  _____  month (1 - 12)
# | | | |  ___  day of week (0 - 6, Sunday - Saturday)
# | | | | | 
# * * * * * command to exectute

# asterisk matches all values
# e.g. daily at midnight
# 0 0 * * * echo 'hello' >> ~/test.txt
# e.g. every minute of every day
* * * * * echo 'hello' >> ~/test.txt

cat ~/test.txt

# to view the actual crontab file
sudo cat /var/at/tabs/darrenkidney
```

`-l` list the current crontabs  
`-u` specify the name of the user whose crontab is to be changed  
`-r` remove the current crontab  
`-e` edit the current crontab


<!-- [Back to top](#top) -->

#### cut {#cut}

Like head and tail but selects colums not rows.

```sh
# print fields 1-5 and 10 from a comma delimited file
cut -f 1-5,10 -d , path/to/file
```

<!-- [Back to top](#top) -->

#### grep {#grep}

print lines matching a pattern

```sh
# match pattern
grep pattern path/to/file

# match pattern1 OR pattern2
grep 'pattern1\|pattern2' path/to/file
grep -E '(pattern1|pattern2)' path/to/file
egrep '(pattern1|pattern2)' path/to/file

# inverse match pattern
grep -v pattern path/to/file

# search the contents of files
grep -rnw 'pattern' path
```

`-c` count the number of matching lines  
`-h` don't print the names of files when searching multiple files  
`-i` case insensitive  
`-l` print the names of files that contain matches, not the matches  
`-n` print line numbers for matching lines  
`-r` recursive
`-v` invert - i.e. show non-matching lines  
`-w` expression is searched for as a word

<!-- [Back to top](#top) -->

#### gzip {#gzip}

* TODO

<!-- [Back to top](#top) -->

#### head {#head}

```sh
# print the first 10 lines of a file
head -n 5 path/to/file

# shorthand
head -5 path/to/file
```

<!-- [Back to top](#top) -->

#### jar {#jar}

* TODO

<!-- [Back to top](#top) -->

#### less {#less}

* like `cat`, but pages output instead of printing everything  
* one page is displayed at a time  
* you can press spacebar to page down or type q to quit  

```sh
less path/to/file
```

* for more than one fileIf you give less the names of several files, you can type  
  * `:n` : move to the next file  
  * `:p` : go back to the previous file  
  * `:q` : quit  

```sh
less path/to/file1 path/to/file2 ...
```

<!-- [Back to top](#top) -->

#### ln {#ln}

```{sh, eval=FALSE}
# create a file link
ln -sv ~/Github/dotfiles/.Rprofile ~
ln -sv ~/Github/dotfiles/.R/snippets/c_cpp.snippets ~/.R/snippets
ln -sv ~/Github/dotfiles/.R/snippets/css.snippets ~/.R/snippets
ln -sv ~/Github/dotfiles/.R/snippets/html.snippets ~/.R/snippets
ln -sv ~/Github/dotfiles/.R/snippets/java.snippets ~/.R/snippets
ln -sv ~/Github/dotfiles/.R/snippets/javascript.snippets ~/.R/snippets
ln -sv ~/Github/dotfiles/.R/snippets/markdown.snippets ~/.R/snippets
ln -sv ~/Github/dotfiles/.R/snippets/python.snippets ~/.R/snippets
ln -sv ~/Github/dotfiles/.R/snippets/r.snippets ~/.R/snippets
ln -sv ~/Github/dotfiles/.R/snippets/sql.snippets ~/.R/snippets
ln -sv ~/Github/dotfiles/.R/snippets/stan.snippets ~/.R/snippets
ln -sv ~/Github/dotfiles/.R/snippets/tex.snippets ~/.R/snippets
```

`-s` symbolic

<!-- [Back to top](#top) -->

#### ls {#ls}

```sh
# list files in the current directory
ls

# list files in a particular directory
ls path/to/file

# print list with extra info
ls -l

# include hidden files
ls -a

# print trailing / after all directories and * after programes
ls -F

# recursive
ls -R

# combine flags
ls -alF
```

<!-- [Back to top](#top) -->

#### man {#man}

```sh
# get help
man ls
```

<!-- [Back to top](#top) -->

#### mkdir {#mkdir} 

```sh
# make a directory
# -p ???
mkdir -p new_dir/new_subdir
cd !$ && pwd
```

<!-- [Back to top](#top) -->

#### pbcopy {#pbcopy}

```sh
# copy to clipboard
pbcopy < ~/.ssh/id_rsa.pub
```

<!-- [Back to top](#top) -->

#### rm {#rm}

```sh
# delete all files/folders in a folder but don't delete the folder
rm -rf path/to/folder/*
```

#### screen {#screen}

http://aperiodic.net/screen/quick_reference  
https://opensource.com/article/17/3/introduction-gnu-screen  
http://www.kinnetica.com/2011/05/29/using-screen-on-mac-os-x  

* useful for managing long-running processes
* can close terminal window or break SSH connection without interrupting the processes
* can have multiple terminal windows within each screen session

```sh
# list existing screens
screen -ls

# start a new screen and give it a name
screen -S test-screen

# start a new screen and give it a name - or attach to exisitng session with that name
screen -R test-screen

# start a new terminal window within the screen session
screen -t test-window1
screen -t test-window2
screen -t test-window3

# detach the screen
screen -d

# re-attach the screen
screen -r test-screen

# kill the attached screen/window 
exit

# kill a detached screen
screen -XS test-screen quit
```

`Ctrl-a ?` help  
`Ctrl-a H` activate screen logging (creates log file `screenlog.0`)  

Terminal windows:

`Ctrl-a i` view which window you are currently using  
`Ctrl-a n` go to the next window
`Ctrl-a p` go to the previous window  

Split panes:

`Ctrl-a S` make a new pane  
`Ctrl-a Q` quit the split pane mode  
`Ctrl-a Tab` switch between panes

<!-- [Back to top](#top) -->

#### scp {#scp}

*TODO*

#### sed {#sed}

Good for one-to-one replacement of strings in files.

*TODO*

#### ssh {#ssh}

*TODO*

#### su {#su}

* switch user

*TODO*

#### sudo {#sudo}

```sh
sudo !!
```

*TODO*

<!-- [Back to top](#top) -->

#### tail {#tail}

```sh
# print the last 5 of a file
tail -n 5 path/to/file

# shorthand
tail -5 path/to/file

# print lines starting from line 5
tail -n +5 path/to/file
```

<!-- [Back to top](#top) -->

#### tar {#tar}

* TODO

<!-- [Back to top](#top) -->

#### touch {#touch}

```sh
# make a file
touch temp.txt
echo "hello" > temp.txt
cat temp.txt
```

<!-- [Back to top](#top) -->

#### unzip {#unzip}

```sh
unzip path/to/file

# list files that would be unzipped but dont unzip
unzip -l path/to/file

# don't overwrite if unzipped file already exists
unzip -n path/to/file

# overwrite without prompting
unzip -o path/to/file

# specify directory
unzip path/to/file -d destination/folder
```

#### vim {#vim}

https://vim.rtorr.com  
https://github.com/hackjutsu/vim-cheatsheet  

edit:

`i` - insert before the cursor  
Esc to exit insert mode  

save and exit:

`:w` write (save) the file (but don't quit)  
`:wq` write (save) and quit  
`:q` quit (fails if there are unsaved changes)  
`:q!` quit and throw away unsaved changes  
`:qa` quit all files (fails if there are unsaved changes)  
`:qa!` quit all files and throw away unsaved changes  

#### wc {#wc}

```sh
# print number of lines, words and bytes
wc path/to/file

# print number of lines
wc -l path/to/file

# print number of words
wc -w path/to/file

# print number of bytes
wc -c path/to/file
```

<!-- [Back to top](#top) -->

******************************************************************************************

### Operators {#operators}

#### pipe {#pipe}

* use the output of the command on the left as the input to the command on the right

```sh
command-one | command-two
```

<!-- [Back to top](#top) -->

#### redirect {#redirect}

* save any command's output somewhere indtead of printing it  
* see [touch](#touch) for an example

```sh
# save output of command to file
command > output-file

# save output of command to file or append to file if it already exists
command >> output-file
```

<!-- [Back to top](#top) -->

******************************************************************************************

### Wildcards {#wildcards}

* `*` match zero or more characters
* `?` match a single character 
* `[...]` matches any of the characters in the square brackets
* `{...}` matches any of the comma-separated patterns inside the brackets, e.g. `{*.txt, *.csv}`

******************************************************************************************

### Variables {#vars}

* `Environment variables` = permanent variables
* `Shell variables` = local variables

```sh
# print all environment variables
set

# example environment variables
echo $PWD
echo $HOME
echo $USER
echo $SHELL

# make a new local variable
DIR=~/Downloads && echo $DIR
cd $DIR && pwd
cd - && pwd

# use the output of a command as a variable
echo 'my zsh is installed here:' $(which zsh)
```

<!-- [Back to top](#top) -->

******************************************************************************************

### For loops {#for-loops}

`for [variable] in [list] ; do [body] ; done`

```sh
# examples
for ext in gif jpg png; do echo $ext; done
for file in dir/*.csv; do echo $file; done
```

******************************************************************************************

### Miscellaneous {#miscellaneous}

```sh
use backslashes \
to break up commands \
across multiple \
lines
```

<!-- [Back to top](#top) -->

******************************************************************************************

### Terminology {#terminology}

<!-- [Back to top](#top) -->

