---
title: "GenomicAlignments"
#author: "Darren Kidney"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: true
#  html_document:
#    toc: true
#    theme: readable
#    highlight: tango
#    keep_md: true
#    lang: "en-GB"
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, encoding = encoding, output_dir = "..")
  })
---

```{r knitr-setup, echo=FALSE}
knitr::opts_chunk$set(
	collapse = TRUE,
	comment = '#',
	message = FALSE,
	strip.white = TRUE
)
```

## links

* https://www.bioconductor.org/packages/devel/bioc/vignettes/GenomicRanges/inst/doc/GenomicRangesIntroduction.html  
* https://kasperdanielhansen.github.io/genbioconductor/html/GenomicRanges_GRanges.html  
* https://kasperdanielhansen.github.io/genbioconductor/html/GenomicRanges_GRanges_Usage.html  
* https://kasperdanielhansen.github.io/genbioconductor/html/GenomicRanges_seqinfo.html  

## example

```{r, message=FALSE}
library(GenomicAlignments)
```

## session info 

```{r}
packageVersion("BiocVersion")
sessionInfo()
```
