---
title: roxygen
output: 
    github_document:
        toc: true
        toc_depth: 4
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  eval = FALSE
)
```

RStudio: `Help > Roxygen Quick Reference`

https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html  
https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html  
https://cran.r-project.org/web/packages/roxygen2/vignettes/formatting.html  
http://r-pkgs.had.co.nz/man.html

```r
install.packages("roxygen2")
```

******************************************************************************************

##### @keywords

see `file.path(R.home("doc"), "KEYWORDS")`

* `internal` - removes the function from the package index and disables some of its automated tests

##### @inheritParams

* `@inheritParams function` - for a function in current package  
* `@inheritParams package::function` - for a function in another package

```{r, eval=TRUE, echo=FALSE, comment="", collapse=TRUE}
library(tidyverse)
templates = dir(system.file("templates", package = "usethis"), full.names = TRUE) %>% 
  keep(str_detect(basename(.), "^package"))
for(temp in templates){
  cat("\n")
  cli::cat_rule(basename(temp),col = "cyan")
  cat("\n")
  writeLines(readLines(temp))
  cat("\n")
}
```