---
title: git
output: 
    github_document:
        toc: true
        toc_depth: 4
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  eval = FALSE
)
```

Commands:

* [git add](#git-add)
* [git annotate](#git-annotate)
* [git branch](#git-branch)
* [git checkout](#git-checkout)
* [git config](#git-config)
* [git clone](#git-clone)
* [git commit](#git-commit)
* [git config](#git-config)
* [git diff](#git-diff)
* [git log](#git-log)
* [git merge](#git-merge)
* [git rebase](#git-rebase)
* [git reset](#git-reset)
* [git revert](#git-revert)
* [git status](#git-status)

Terminology:

* [blob](#blob)
* [branch](#branch)
* [commit](#commit)
* [hash](#hash)
* [HEAD](#head)

******************************************************************************************

https://git-scm.com/docs
https://git-scm.com/book/en/v2  
https://happygitwithr.com/  

******************************************************************************************

```sh
# install 
brew install git
# check installation
git --version
which git
```

******************************************************************************************

### Commands

#### git add {#git-add}

```sh
# add a file to the staging area
git add path/to/file
```

#### git annotate {#git-annotate}

A bit like [git log](#git-log) but shows more information.

```sh
git annotate file
```

#### git branch {#git-branch}

```sh
```

#### git checkout {#git-checkout}

```sh
# discard the changes to a particular file that have not been staged
git checkout --path/to/file

# replace the current version of a file with the version in commit xxxxx
git checkout xxxxx path/to/file
```

#### git clone {#git-clone}

```sh
```

#### git commit {#git-commit}

```sh
# save the changes in the staging area
git commit

# use a commit message
git commit -m "infrmtv mssg"

# change the commit message
git commit --amend - m "informative message"
```

#### git config {#git-config}

View or change default settings.

* `--system` : settings for every user
* `--global` : settings for current user
* `--local` : settings for current project

```sh
# view all settings
git config --list --system
git config --list --global # overrides system
git config --list --local # overrides global

# view a particular setting
git config --system user.name
git config --global user.name
git config --local user.name

# change a particular setting
git config --global user.name dkidney
```

#### git diff {#git-diff}

Compare differences between revisions.

```sh
# show all unstaged changes in working copy files
git diff

# show differences between staged files and the last commit
git diff --staged

# show differences between working copy files and those in a particular revision
# e.g the most recent commit
git diff -r HEAD

# show differences between a particular working copy file and that in a particular revision
# e.g the most recent commit
git diff -r HEAD path/to/file

# show differences between two branches
git diff master..contact-form

# show differences between two commits
git diff 0023cdd..fcd6199

# show differences between the previous commit and the one before that
git diff HEAD~1..HEAD~2
```

#### git log {#git-log}

```sh
# view a project's history
git log

# view a history for a particular file or directory
git log path

# view a the last three items in the history for a particular file or directory
git log -3 path
```

#### git merge {#git-merge}

```sh
```

#### git rebase {#git-rebase}

```sh
```

#### git reset {#git-reset}

```sh
# unstage all unstaged files
git reset HEAD

# unstage a particular unstaged file
git reset HEAD path/to/file
```



#### git revert {#git-revert}

```sh
```

#### git show {#git-show}

View the details of a specific commit

```sh
git show 0da2f7
```

#### git status {#git-status}

Shows you:

* which files are in the staging area  
* which files have changes that haven't yet been staged  

```sh
git status
```

******************************************************************************************

### Terminology

#### blob {#blob}

Short for *binary large object* - an SQL database term for "may contain data of any kind".

#### branch {#branch}

#### commit {#commit-term}

* contains metadata such as the author, the commit message, and the time the commit happened

* each commit has a tree, which tracks the names and locations in the repository when that commit happened

* for each of the files listed in the tree, there is a [blob](#blob) which contains a compressed snapshot of the contents of the file when the commit happened

#### hash {#hash}

* a unique identifier associated with a commit

* generated by running the changes through a pseudo-random number generator (ash function)

* normally written as a 40-character hexadecimal string

* most of the time you only have to give Git the first 6 or 8 characters of the hash

* they enable Git to share data efficiently between repositories - if two commits contain the same files and have the same ancestors, they will have the same hash

#### HEAD {#head}

* a special label that refers to the most recent commit

* `HEAD~1` refers to the commit before `HEAD`

* `HEAD~2` refers to the commit before `HEAD~1`

******************************************************************************************

```sh
# check commit history
git log

# check status
git status

# checkout onto a branch
git checkout [branch-name]

# clone a repo via https
git clone https://github.com/USERNAME/REPOSITORY.git

# Check it was cloned successfully:
git remote --verbose

# commit a change
git add foo.txt
git commit --message "A commit message"

# make a branch
git branch [branch-name]
git checkout [branch-name]

# merge a branch
# E.g. merge into master:
git checkout master
git merge [branch-name]

# osxkeychain helper
git credential-osxkeychain

# Tell Git to use osxkeychain helper:
git config --global credential.helper osxkeychain

# stash changes
# E.g. when pulling conflicting changes:
git stash
git pull
git stash pop
```
