# cli

***

## git

### FAQs

* unstage files but don't undo the changes

### terminology

#### HEAD {-#head}

The snapshot of your last commit on the current branch

`HEAD` =  
`HEAD^` =  
`HEAD~1` =   
`HEAD~2` =   

#### index {-#index}

I.e.the staging area = your proposed next commit

#### working directory {-#workingdir}

Aka **working tree** = a sandbox, where you can try changes out before committing them to your staging area (index)

### `git reset` {#reset}

* undo commits by reseting the current [HEAD](#head) to a previous state (specified by `<commit>`)  
* deletes commits, unlike [git revert](#revert) which makes a new commit

#### mode {-} 

mode      | reset HEAD | reset index | reset working tree
--------- | ---------- | ----------- | ------------------
`--soft`  | YES        | NO          | NO   
`--mixed` | YES        | YES         | NO   
`--hard`  | YES        | YES         | YES   

#### examples {-}

```sh
git reset --soft HEAD~1 # undo the last commit but KEEP file changes
git reset --hard HEAD~1 # undo the last commit and UNDO file changes
git reset --hard 12345678 # roll back to commit 12345678
git reset myfile.txt   # remove myfile.txt from the staging area but KEEP changes
```

### `git restore` {#restore}

* undo a `git add`

#### examples {-}

```sh
git restore --staged myfile.txt  # remove myfile.txt from the staging area but KEEP changes
git restore myfile.txt           # remove myfile.txt from the staging area and UNDO changes
```

### `git revert` {#revert}

* undo commits by creating a new 'reverting commit`
* unlike [git reset](#reset) which deletes commits

#### examples {-}

```sh
```

### `.gitignore`

***

## bash

### variables

### arrays

### for loops

***

## awscli

### FAQs

copy only files with specific file extension

copy all files except those with a specific file extension


