---
title: bash
---

```{css css_custom, code=readLines("_css_custom.css"), echo=FALSE}
```
```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

> Bourne-again shell

*********************************************************************

* https://devhints.io/bash  

*********************************************************************

## scripts

```sh
bash script.sh > output.out
```

* `$1` first command-line parameter given to the script
* `$2` second command-line parameter given to the script
* `$@` all of the command-line parameters given to the script


*********************************************************************

## redirection {#redirect}

```sh
# redirect output of command to file
command > output-file

# redirect output of command to file (append to file if file already exists)
command >> output-file

# redirect stdout and stderr to output file
command > output-file 2>&1
```

* file descriptor `1` is the standard output (stdout)  
* file descriptor `2` is the standard error (stderr)  
* `2` : refers to the second file descriptor (i.e. stderr)  
* `>` :  means redirection  
* `&1` : means the target of the redirection should be the same location as the first file descriptor (i.e. stdout)  


*********************************************************************

## wildcards {#wildcards}

* `*` match zero or more characters
* `?` match a single character 
* `[...]` matches any of the characters in the square brackets
* `{...}` matches any of the comma-separated patterns inside the brackets, e.g. `{*.txt, *.csv}`

*********************************************************************

## variables {#vars}

* `Environment variables` = permanent variables
* `Shell variables` = local variables

```{sh}
# shell version
echo $SHELL
```

```sh
# print all environment variables
set

# example environment variables
echo $PWD
echo $HOME
echo $USER
echo $SHELL

# make a new local variable
DIR=~/Downloads && echo $DIR
cd $DIR && pwd
cd - && pwd

# use the output of a command as a variable
echo 'my zsh is installed here:' $(which zsh)
```


*********************************************************************

## loops {#loops}

`for [variable] in [list] ; do [body] ; done`

```sh
# examples
for ext in gif jpg png; do echo $ext; done
for file in dir/*.csv; do echo $file; done
```

*********************************************************************

## multiple lines

### single command

```sh
use backslashes \
to break up commands \
across multiple \
lines
```

### multiple commmands

`|` : the (standard) output of the command on left are used as the (standard) input to the command on right

`;` : command on right executed once the command on left has terminated

`&&` : command on right is only executed if the command on left returns an exit status of zero

`||` : command on right is only executed if the command on left returns an exit status of non-zero

`&` : command on left is executed the background - the shell does not wait for the command to finish and immediately returns exit code 0

`|&` : shorthand for `2>&1` - both standard output and standard error of command on left are are used as the (standard) input to the command on right


*********************************************************************

## EOF

TODO

