---
title: conda
---

```{css css_custom, code=readLines("_css_custom.css"), echo=FALSE}
```
```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

> an open source package management system and environment management system

*********************************************************************

* https://docs.conda.io (home)  
* https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf (cheatsheet)  
* https://www.datacamp.com/community/tutorials/installing-anaconda-mac-os-x (datacamp)  

*********************************************************************

## installation

### homebrew cask

* installs to `~/usr/local/anaconda3/` by default

```sh
brew cask install anaconda

# update the PATH definition in .zshrc / .bash_profile
echo '' >> ~/.zshrc
echo '# conda' >> ~/.zshrc
echo 'export PATH=/usr/local/anaconda3/bin:"$PATH"' >> ~/.zshrc 

# initialize your zsh/bash profile
conda init zsh
conda init bash
```

update conda - *warning: this will delete all your conda environments!*

```sh
brew cask upgrade anaconda
```

### macOS installer

* https://www.anaconda.com/distribution/#macos

* installs to `~/anaconda3/` by default

* I think this automatically updates your `~/.bash_profile` with a `>>> conda init >>>` or `>>> conda initialise >>>` section (you might need to copy this section into your `~/.zshrc`)

update conda

```sh
conda update -n base -c defaults conda
```

### check installation

```sh
conda --version
which conda # doesn't work...
conda info

# get help
conda --help
conda install --help
```

### uninstall

```sh
# remove the configs
conda install anaconda-clean
anaconda-clean --yes 
# creates a backup folder which you can also remove if you want to
rm -rf ~/.anaconda_backup

# unstall anaconda
brew cask uninstall anaconda
```

If you installed via a method other than brew cask you may need to manually remove the anaconda install folder and 

```sh
rm -rf ~/anaconda3
```

You will also need to remove the `>>> conda init >>>` section in `~/.bash_profile` and `~/.zshrc`.

*********************************************************************

## py envs

```sh
# latest python version
conda search python | tail -1

# anaconda installation directory
echo $CONDA_PREFIX

# list all environments
conda env list
conda info --envs

# create new environments (see also note below)
conda create --name py2 python=2.7.12 
conda create --name py3 python=3.7.4

# activate an environment
conda activate py3
python --version
which python

# deactivate an environment
conda deactivate
python --version
which python

# update python version for the current environment
conda update python

# delete an environment
conda env remove --name py2

# add a line to .zshrc/.bash_profile to use a particular env by default (if you want to)
echo 'conda activate py3' >> ~/.zshrc
echo 'conda activate py3' >> ~/.bash_profile
```

Note: if you get a **CondaHTTPError: HTTP 000 CONNECTION FAILED** error, try running this:

```sh
conda config --set ssl_verify no
```


*********************************************************************

## py libs

```sh
# list all package versions installed in active environment
conda list

# install a package or packages to the current
conda install numpy

# update a package in the active environment
conda update numpy

# update all packages in the active environment
conda update --all

# install a package or packages to a named environment
conda install --name py3 \
#airflow \
#binarytree \
#boto3 \
#graphviz \
#ipykernel \
keras \
matplotlib \
numpy \
pandas \
#parquet-cpp \
#pyarrow \
pyhocon \
pymysql \
#python-graphviz \
seaborn \
#selenium \
scikit-learn \
scipy \
#snowflake-connector-python \
statsmodels \
xmltodict

# update all packages in a named environment
conda update --all --name py3
```

### channels

```sh
# allow installation of conda-forge packages
conda config --add channels conda-forge
```

examples

```sh
conda install --name py3  -c conda-forge airflow
conda install --name py3  -c conda-forge binarytree
conda install --name py3  -c conda-forge jira
conda install --name py3  -c conda-forge pyspark
#conda install --name py3  -c conda-forge snowflake-connector-python
conda install --name py3  -c conda-forge xgboost
```

### requirements

```sh
conda install --name py3 -c conda-forge --file requirements.txt
```

