---
title: java
---

```{css css_custom, code=readLines("_css_custom.css"), echo=FALSE}
```
```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

## installation

```sh
brew tap caskroom/versions

# look for installable versions
brew search java 

# install the version(s) you want
brew cask install java8
brew cask install java11

# check default version
java -version
which java
```



*********************************************************************

## managing versions

```sh
# find locations of previously installed Java JDK's installed at the default system locations
/usr/libexec/java_home -V
```

## JAVA_HOME

in .zshrc add

`export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home"`


*********************************************************************

## r

```r
install.packages("rJava")
```

```sh
# reconfigue Java
R CMD javareconf # need to restart RStudio after this has run
```

```{r}
Sys.getenv("DYLD_FALLBACK_LIBRARY_PATH")
Sys.getenv("DYLD_LIBRARY_PATH")
```


# jenv

jenv enable-plugin export


*********************************************************************

https://www.w3schools.com/java/default.asp
https://stackoverflow.com/questions/52524112/how-do-i-install-java-on-mac-osx-allowing-version-switching
http://davidcai.github.io/blog/posts/install-multiple-jdk-on-mac/
http://www.lonecpluspluscoder.com/2017/04/27/installing-java-8-jdk-os-x-using-homebrew/
http://www.lonecpluspluscoder.com/2017/10/08/installing-other-versions-of-the-java-jdk-via-homebrew/
