---
title: pycharm
---

```{css css_custom, code=readLines("_css_custom.css"), echo=FALSE}
```
```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

> an integrated development environment specifically for python - developed by the Czech company JetBrains - the community edition provides an intelligent editor, graphical debugger, refactorings, code inspections and version control integration

*********************************************************************

* https://www.jetbrains.com/help/pycharm/meet-pycharm.html  

*********************************************************************

## installation 

```sh
brew cask install pycharm-ce
```

*********************************************************************

## project setup

### make a new py file

within the project, right click on the project folder and then click `New > Python file`

### set the interpreter 

e.g. to an existing conda env

- `PyCharm >`  
- `Preferences >`  
- `Project: [my project] >`  
- `Project Interpreter >`  
- `Project Interpreter... >`  
- `[Settings wheel] >`  
- `Add... >`  
- `Conda Environment >`  
- `Existing Environment >`  
- `Interpreter`  

can choose `make available to all projects`

*Dont forget to `Apply` before clicking `Ok`*

### run script

`Run > Run > `

then either 

`select file from drop down` to use existing interpreter etc

or 

`edit configurations` to change interpreter and/or command args etc.


*********************************************************************

## shortcuts

- `PyCharm >`  
- `Preferences >`  
- `Appearances & Behaviour >`  
- `Keymap`  

shortcut  | action
------------- | -------------
CTRL + R | source script
CTRL + SPACE | help with code completion
CTRL + UP/DOWN | move between methods in editor
 | 
CMD + B | jump to function definition
CMD + E | opens a popup of recently visited files
CMD + P | view parameter info

*********************************************************************

git integration

themes & color schemes

