---
title: r topics
---

```{css css_custom, code=readLines("_css_custom.css"), echo=FALSE}
```
```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

## match

TODO

*********************************************************************

## replace

```{r, eval=TRUE}
x = c(a = 2)
defaults = c(a = 1, b = 2)
replace(defaults, names(x), x)
```

*********************************************************************

## Rscript {#rscript}

https://support.rstudio.com/hc/en-us/articles/218012917-How-to-run-R-scripts-from-the-command-line

```sh
# raw expressions
Rscript -e 'print("hello")'

# scripts
Rscript ~/my_script.R

# options 
Rscript --vanilla ~/my_script.R

# as above, but allows renviron
Rscript --no-save --no-restore --no-site-file --no-init-file ~/my_script.R
```

Need to use this header in the script 

```
#!/usr/bin/Rscript
```

### optparse

http://www.cureffi.org/2014/01/15/running-r-batch-mode-linux/

TODO


*********************************************************************

## spinners

```r
# use a spinner while waiting for a function to run 
wait = function(){
  Sys.sleep(5)
  "hello"
}
callr::r(wait, spinner = TRUE)
```

*********************************************************************

## environment variables

R_MAX_MEM_SIZE  

R_MAX_VSIZE  

R_VSIZE  

R_NSIZE  

### rstudio

RSTUDIO_CONSOLE_WIDTH

## clipboard

read from clipboard

```r
readr::read_tsv(pipe("pbpaste"))
```

write to clipboard

```r
my.data <- data.frame(x = c(1,1,2,3), 
                   y = c(1,1, 3, 4), 
                   z = c(1,4,6,7))
clip <- pipe("pbcopy", "w")                       
write.table(my.data, file=clip, sep = '\t', row.names = FALSE)
close(clip)
```

for Windows:

https://www.johndcook.com/blog/r_excel_clipboard/

*********************************************************************

## reticulate

https://rstudio.github.io/reticulate/index.html

*********************************************************************

Rcpp/c

*********************************************************************

R6

*********************************************************************

Htmltools

*********************************************************************

Stan

*********************************************************************

Plumber


