---
title: Geospatial
output: 
    github_document:
        toc: true
        toc_depth: 4
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  eval = FALSE
)
```

******************************************************************************************

## geosphere

### distVincentyEllipsoid

******************************************************************************************

## mapdata

```{r, eval=FALSE}
library(mapdata)
data(worldHiresMapEnv)
```

******************************************************************************************

## maps

```{r, eval=FALSE}
library(maps)
map(
  "worldHires",
  xlab = "lon",
  ylab = "lat",
  regions = "south africa",
  xlim = c(15, 34),
  ylim = c(-35, -22),
  fill = TRUE,
  col = "grey95",
  mar = c(0, 0, 0, 1)
)
```

## map.scale

******************************************************************************************

## maptools

### readShapePoly

******************************************************************************************

## osmdata

******************************************************************************************

## sf

******************************************************************************************

## sp

### SpatialPolygons

******************************************************************************************

## rgdal

### CRS

E.g.

asdf | asdf
------------- | -------------
"+init=epsg:27700"   | OSGB easting / northing
"+proj=longlat"      | latitude / longitude
"+proj=utm +zone=30" | utm 30 (UK?)  
"+proj=utm +zone=48" | utm 48 (Cambidia?)  

```{r}

```

### readOGR

### spTransform

```{r}

```

******************************************************************************************

## rgeos

### gDIfference

### gDistance

### gIntersection

### gUnionCascaded

******************************************************************************************

