---
title: R
output: 
    github_document:
        toc: true
        toc_depth: 4
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  eval = FALSE
)
```


<!-- * [Rscript](#rscript) -->


******************************************************************************************

#### match

******************************************************************************************

#### replace

```{r, eval=TRUE}
x = c(a = 2)
defaults = c(a = 1, b = 2)
replace(defaults, names(x), x)
```

******************************************************************************************

#### Rscript {#rscript}

https://support.rstudio.com/hc/en-us/articles/218012917-How-to-run-R-scripts-from-the-command-line

```sh
# raw expressions
Rscript -e 'print("hello")'

# scripts
Rscript ~/my_script.R

# options 
Rscript --vanilla ~/my_script.R

# as above, but allows renviron
Rscript --no-save --no-restore --no-site-file --no-init-file ~/my_script.R
```

Need to use this header in the script 

```
#!/usr/bin/Rscript
```

##### optparse

http://www.cureffi.org/2014/01/15/running-r-batch-mode-linux/

TODO


******************************************************************************************

#### spinners

```r
# use a spinner while waiting for a function to run 
wait = function(){
  Sys.sleep(5)
  "hello"
}
callr::r(wait, spinner = TRUE)
```

******************************************************************************************

#### environment variables

R_MAX_MEM_SIZE  

R_MAX_VSIZE  

R_VSIZE  

R_NSIZE  

##### rstudio

RSTUDIO_CONSOLE_WIDTH
