---
title: matrices
---

```{css css_custom, code=readLines("_css_custom.css"), echo=FALSE}
```
```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

## inverse

```{r}
n <- 5
A <- matrix(0.2, ncol = n, nrow = n)
diag(A) <- 1
A
A_inv <- solve(A)
round(A %*% A_inv, 10)
```

to do:

```
Sigma_inv <- chol2inv(chol(Sigma))
```

*********************************************************************

## inverse square root

```{r}
n <- 5
A <- matrix(0.2, ncol = n, nrow = n)
diag(A) <- 1
A
```

```{r}
inv_sqrt_mat <- function(x) {
  E <- eigen(x)
  if (!all(E$values > 0)) {
    stop("Matric must be positive semi-definite")
  }
  x_sqrt <- E$vectors %*% diag(sqrt(E$values)) %*% t(E$vectors)
  solve(x_sqrt)
}
```

```{r}
A_inv <- inv_sqrt_mat(A)
A_inv
```

```{r, eval=FALSE}
A %*% A_inv
A %*% t(A_inv)
t(A) %*% A_inv
t(A) %*% t(A_inv)
```

*********************************************************************

## ldl

TODO

*********************************************************************

## positive semi-definite

TODO

*********************************************************************

## cholesky

TODO

*********************************************************************

## qr

TODO

*********************************************************************

## variance-correlation

```{r}
n <- 5
sigma <- sqrt(2)
corr <- 0.5
var_mat <- diag(n) * sigma^2
var_mat
cor_mat <- matrix(corr, ncol = n, nrow = n)
diag(cor_mat) <- 1
cor_mat
cov_mat <- sqrt(var_mat) %*% cor_mat %*% sqrt(var_mat)
cov_mat
identical(cor_mat, stats::cov2cor(cov_mat))
```


