---
title: reticulate
subtitle: (R)
editor_options: 
  chunk_output_type: console
---

```{css css_custom, code=readLines("_css_custom.css"), include=FALSE}
```
```{r knitr_config, code=readLines("_knitr_config.R"), include=FALSE}
```
```{r, include=FALSE}
library(reticulate)
```

*********************************************************************

* https://rstudio.github.io/reticulate/index.html  

*********************************************************************

## python version

Identify the version / environment you're currently using

```{r}
py_info = py_discover_config()
py_info
```

```{r}
py_info$python
py_info$libpython
py_info$pythonhome
py_info$virtualenv
py_info$virtualenv_activate
py_info$version_string
py_info$version
py_info$architecture
py_info$anaconda
py_info$numpy$path
py_info$numpy$version
py_info$required_module
py_info$required_module_path
py_info$available
py_info$python_versions
py_info$forced
```

Set / change python version / environment

```{r, eval=FALSE}
# need to restart R first if another py version has alread been initialised
# if required = FALSE no warning is given if the version doesn't exist
use_python("/usr/local/anaconda3/envs/py3/bin/python", required = TRUE)
```

*********************************************************************

## library versions

```{r}
xmltodict = try(import("xmltodict"), TRUE)
if (inherits(xmltodict, "try-error")) {
    cat("No module named 'xmltodict'")
}else{
    cat("xmltodict version", xmltodict$"__version__", "\n")
}
```
