---
title: "rgdal"
---

```{css css_custom, code=readLines("_css_custom.css"), echo=FALSE}
```
```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```
```{r, echo=FALSE}
library(tidyverse)
library(rgdal)
```

*********************************************************************

> R Geospatial Data Abstraction Library

*********************************************************************

* https://cran.r-project.org/package=rgdal

*********************************************************************

## readOGR

TODO 

*********************************************************************

## writeOGR

TODO 

*********************************************************************

## spTransform

To transform from one CRS to another:
newData <- spTransform(x, CRS("+init=epsg:4238"))
or, reference the CRS of another spatial object:
newData <- spTransform(x, proj4string(OtherData))

*********************************************************************

## make_EPSG

Lists all the available EPSG (European Petroleum Survey Group) codes for CRS proj4strings.

```{r}
make_EPSG() %>% as_tibble
```

*********************************************************************

## projInfo

Lists all the different options for CRS proj4string attributes.

### proj

```{r}
projInfo(type = "proj") %>% as_tibble
```

### datum

```{r}
projInfo(type = "datum") %>% as_tibble
```

### ellps

```{r}
projInfo(type = "ellps") %>% as_tibble %>% tail
```

### units

```{r}
projInfo(type = "units") %>% as_tibble
```
