---
title: s4
---

```{css css_custom, code=readLines("_css_custom.css"), echo=FALSE}
```
```{r knitr_config, code=readLines("_knitr_config.R"), echo=FALSE}
```

*********************************************************************

* http://adv-r.had.co.nz/S4.html  

*********************************************************************

## create an instance

### `dgCMatrix`

Create a normal matrix.

```{r}
mat = matrix(c(1,0,0,0,1,0,0,0,1,0,1,0), 4, 3, byrow = TRUE)
mat
```

Convert to `dgCMatrix`.

```{r}
index = which(mat == 1, arr.ind = TRUE)
smat = Matrix::sparseMatrix(
  i = index[,1], 
  j = index[,2], 
  x = 1,
  dims = dim(mat),
  dimnames = dimnames(mat)
)
smat
str(smat)
```

Create the same object from scratch.

```{r}
smat2 = new(
  Class = "dgTMatrix",
  i = index[,1] - 1L,
  j = index[,2] - 1L,
  Dim = dim(mat),
  Dimnames = list(NULL, NULL),
  x = rep(1, nrow(index)),
  factors = list()
)
smat2 = as(smat2, "dgCMatrix")
identical(smat, smat2)
```

*********************************************************************

## create a class

```{r, eval=FALSE}
?setClass
```

*********************************************************************

showDefault for S4?

